### PR TITLE
Commands and command groups fixes

### LINKED ISSUE #46: RotateDrivetrain might produce a null pointer exception
As it uses desiredVelocity but it's never initialized

### PR DESCRIPTION
**Pull request by EliyaFishman**
Fixes #46

### CODE REVIEW

File: src/main/java/frc/robot/commands/RunTwoCommands.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+ */
+public class RunTwoCommands extends CommandBase {
+    private Command ifTrue;
+    private Command ifFalse;
+    private Command runningCommand;
+    private BooleanSupplier condition;
+    private boolean lastConditionState;
+
+    /**
+     *
```
Comment (HilelAmiel) [inline src/main/java/frc/robot/commands/RunTwoCommands.java]: blank line

File: src/main/java/frc/robot/commands/RunTwoCommands.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+        this.condition = condition;
+        m_requirements.addAll(ifFalse.getRequirements());
+        m_requirements.addAll(ifTrue.getRequirements());
+    }
+
+    @Override
+    public void initialize() {
+        lastConditionState = condition.getAsBoolean();
+        runningCommand = lastConditionState ? ifTrue : ifFalse;
+        runningCommand.initialize();
```
Comment (HilelAmiel) [inline src/main/java/frc/robot/commands/RunTwoCommands.java:35]: why not use `.schedule();` and `.cancel();` ? I think it would save you initialize and execute lines

File: src/main/java/frc/robot/commands/RunTwoCommands.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+
+    /**
+     *
+     * @param ifTrue command to run if the condition is true
+     * @param ifFalse command to run if the condition is false
+     * @param condition a supplier of the condition
+     */
+    public RunTwoCommands(Command ifTrue, Command ifFalse, BooleanSupplier condition) {
+        this.ifTrue = ifTrue;
+        this.ifFalse = ifFalse;
```
Comment (HilelAmiel) [inline src/main/java/frc/robot/commands/RunTwoCommands.java:25]: what if ifTrue or ifFalse commands are **null**?

File: src/main/java/frc/robot/constants/robots/RobotA.java [hunk 4]
```diff
@@ -69,6 +69,8 @@ public RobotA() {
         loaderConstants.kDefaultVelocity = 0.5;
         loaderConstants.kStallLimit = 20;
         loaderConstants.kSpinBackwardsTime = 1;
+        loaderConstants.kDefaultBackwardsPower = 0.2;
```
Comment (HilelAmiel) [inline src/main/java/frc/robot/constants/robots/RobotA.java]: **-** 0.2?

File: src/main/java/frc/robot/constants/RobotConstants.java [hunk 5]
```diff
@@ -58,6 +58,8 @@
         public double kTicksPerRotation;
         public double kDefaultVelocity;
         public double kSpinBackwardsTime;
+        public double kDefaultBackwardsPower;
+        public double kDefaultUnjamPower;
```
Comment (HilelAmiel) [inline src/main/java/frc/robot/constants/RobotConstants.java]: public double kDefaultUnjamPower;
what is Unjam?

File: src/main/java/frc/robot/commands/command_groups/AutoShoot.java [hunk 6]
```diff
@@ -54,11 +54,9 @@ public AutoShoot(DoubleSupplier speedSupplier, boolean isAuto) {
                 setShooterVelocity,
                 new SpinMixer(),
                 turnToTarget,
-                sequence(
-                    new WaitUntilCommand(() -> setShooterVelocity.isOnTarget() && turnToTarget.isOnTarget()),
-                    SetLoaderVelocity.defaultSetLoaderVelocityCommand()
-                )
-            )
+                new RunTwoCommands(SetLoaderVelocity.defaultSetLoaderVelocityCommand(),
```
Comment (HilelAmiel) [inline src/main/java/frc/robot/commands/command_groups/AutoShoot.java]: add another tolerance for this condition

File: src/main/java/frc/robot/subsystems/drivetrain/RotateDrivetrain.java [hunk 7]
```diff
@@ -16,6 +16,7 @@
      */
```
Comment (HilelAmiel) [inline src/main/java/frc/robot/subsystems/drivetrain/RotateDrivetrain.java:16]: A suggestion, add DriveWithXbox as default command

**Review by HilelAmiel — CHANGES_REQUESTED** [review]
change

**Comment by EliyaFishman** [comment]
[Commands fixes](https://trello.com/c/oYbBJiE3/144-commands-fixes)

**Comment by EliyaFishman** [comment]
[Commands fixes](https://trello.com/c/oYbBJiE3/144-commands-fixes)

File: src/main/java/frc/robot/OI.java [hunk 8]
```diff
@@ -39,7 +43,7 @@ public OI() {
         }, EntryListenerFlags.kNew | EntryListenerFlags.kImmediate | EntryListenerFlags.kUpdate);
     }
     private void createDriverCommands() {
-        //TODO create driver commands here
+        drivetrain.setDefaultCommand(new DriveWithXbox(() -> driverXbox.getX(Hand.kLeft), () -> driverXbox.getY(Hand.kLeft)));
```
Comment (HilelAmiel) [inline src/main/java/frc/robot/OI.java]: no.







you should make y as the deltaTriggers value...

**Review by HilelAmiel — APPROVED** [review]
