### PR TITLE
Null pointer exceptions  hotfix

### LINKED ISSUE #52: Auto Shoot Generate Null Pointer Exception

### PR DESCRIPTION
**Pull request by HilelAmiel**
fixes #52 
- AutoShoot null pointer
- OI null pointer fix
- order TurnToTarget command

### CODE REVIEW

File: src/main/java/frc/robot/Robot.java [hunk 1]
```diff
@@ -55,8 +55,8 @@ public void robotInit() {
         led = new LED();
 
         // Utils:
-        dashboardDataContainer = new DashboardDataContainer();
         limelight = new Limelight();
+        dashboardDataContainer = new DashboardDataContainer();
```
Comment (EliyaFishman) [inline src/main/java/frc/robot/Robot.java]: move container to after OI. we might want to send a command that uses a controller

**Review by EliyaFishman — CHANGES_REQUESTED** [review]
What happens to TurnToTarget if the robot isn't facing the target?

**Review by EliyaFishman — APPROVED** [review]
